name: Telegram ChatAnalyzerBot Heroku deployment

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 21.3.0
      - name: Build image
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: dockerBuildNative

      - name: Deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          email: ${{secrets.HEROKU_EMAIL}}

