name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          distribution: 'graalvm' 

      - name: Run gradle build   
        run:  cd Webhook/ChatAnalyzerBot && ./gradlew build
        
      - name: Test Report
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: Webhook/ChatAnalyzerBot/build/test-results/test/*.xml  
        
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          distribution: 'graalvm' 

      - name: Run image build   
        run:  cd Webhook/ChatAnalyzerBot && ./gradlew dockerBuildNative

      - name: Deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          email: ${{secrets.HEROKU_EMAIL}}             
          dockerfile_directory: Webhook/ChatAnalyzerBot/build/docker/native-main
          dockerfile_name: DockerfileNative
        