name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup working dir
        run:  cd Webhook/ChatAnalyzerBot
      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 17
          distribution: 'graalvm'
      - name: Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: compileJava

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: test
      - name: Test Report
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/test/*.xml

  deploy:
    needs: test 
    runs-on: ubuntu-latest
    steps:       
      - name: Build image
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: dockerBuildNative
        
      - name: Deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: ${{secrets.HEROKU_APP}}
         email: ${{secrets.HEROKU_EMAIL}}        